### ISSUE TITLE
MemCache, LocalCache and RemoteCache for PartialDatabase

### ISSUE THREAD

**Issue by bkordan** [simulpong/RobloxLabsTemp#1]
**Is your feature request related to a problem? Please describe.**
There is a problem with the partial database right now, there is literally 0 caching on it, not even a single piece of memcache.
This will make issues rise when mass reading from a database. If we are ever using a remote data base, having a lot of reads per second can up db costs and impede on the performance of the host computer and the remote computer etc.

**Describe the solution you'd like**
I would like us to try and implement at least a Memcached repository for Roblox.Mssql.PartialDatabase, or EntityBase.
I have layed the steps out here: https://jira.mfdlabs.local/projects/MEMCACHE/summary

**Describe alternatives you've considered**
Alternatives include LocalCache, but that should only be looked at when MemCache is implemented and tested fully.

**Additional context**
https://jira.mfdlabs.local/projects/MEMCACHE/summary
https://jira.mfdlabs.local/projects/CACHEMYMOM/summary
https://git.backlog.mfdlabs.local/ui/mfdlabs/robloxlabs/summit-total-request-time?includeInUtc=true
https://gpc.ark-vm-tester.mfdlabs.local/ui/robloxlabs/metrics-influx?field=request-time&category=sql&provider=mysql
https://ark-testers.who-owns-this-sector.mfdlabs.local/ark/vm-processes/robloxlabs/172/metrics-total?count=true
https://git.metrics-park.mfdlabs.local/mfdlabs/robloxlabs/runner-metrics-influx?q=SqlQuery
https://git-action-runners.statping.mfdlabs.local/mfdlabs/robloxlabs/721/metrics

**Comment by nkpetko** [comment]
CACHEMYMOM, nice choice for a project name

**Comment by bkordan** [comment]
@nkpetko Look at how fucking slow it is when we don't cache retard.

**Comment by nkpetko** [comment]
Jake and I done:
https://github.com/simulpong/RobloxLabsTemp/commit/2a7b83995dbf4b44010baf464354687bf61f856c
